{{- if .Values.mluExporter.needServiceMonitoring }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "mlu-exporter.labels" . | nindent 4 }}
  name: {{ include "mlu-exporter.fullname" . }}
  namespace: {{ include "mlu-exporter.namespace" . }}
spec:
  endpoints:
  - honorLabels: true
    interval: 15s
    port: http-metrics
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: exported_node
    metricRelabelings:
    - sourceLabels: [exported_node]
      targetLabel: node
    - action: labeldrop
      regex: exported_node
  jobLabel: component
  namespaceSelector:
    matchNames:
    - {{ include "mlu-exporter.namespace" . }}
  selector:
    matchLabels:
      {{- include "mlu-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
