FROM ghcr.io/flant/shell-operator:v1.6.2 AS shell-operator

FROM python:3.10-alpine3.23

ENV ARCH=amd64

# 使用国内镜像源加速
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk --no-cache add yq bash curl unzip openssl && \
    apk --no-cache add gcc libffi-dev openssl-dev musl-dev && \
    export CRYPTOGRAPHY_DONT_BUILD_RUST=1 && \
    pip install --no-cache-dir ansible_runner==2.2.0 ansible==2.9.27 kubernetes --use-deprecated=legacy-resolver && \
    apk del gcc libffi-dev openssl-dev musl-dev && \
    if [[ $(arch) == aarch64* ]]; then ARCH=arm64; fi && \
    wget https://get.helm.sh/helm-v3.9.0-linux-${ARCH}.tar.gz && \
    tar -zxf helm-v3.9.0-linux-${ARCH}.tar.gz && \
    mv linux-${ARCH}/helm /bin/helm && \
    rm -rf *linux-${ARCH}* && \
    chmod +x /bin/helm && \
    wget https://storage.googleapis.com/kubernetes-release/release/v1.23.7/bin/linux/${ARCH}/kubectl -O /bin/kubectl && \
    chmod +x /bin/kubectl && \
    ln -s /bin/kubectl /usr/local/bin/kubectl && \
    ln -s /bin/helm /usr/local/bin/helm && \
    mkdir -p /hooks/kubesphere /kubesphere/installer/roles /kubesphere/results/env /kubesphere/playbooks /kubesphere/config &&\
    adduser -D -g kubesphere -u 1002 kubesphere

COPY --from=shell-operator /frameworks/shell /frameworks/shell
COPY --from=shell-operator /shell_lib.sh /shell_lib.sh
COPY --from=shell-operator /shell-operator /shell-operator
COPY --from=shell-operator /usr/bin/jq /usr/bin/jq

ADD controller/* /hooks/kubesphere/

RUN chown -R kubesphere:kubesphere /shell-operator && \
    chown -R kubesphere:kubesphere /hooks && \
    chown -R kubesphere:kubesphere /kubesphere && \
    chmod +x -R /hooks/kubesphere && \
    mkdir -p /var/run/shell-operator && \
    chown -R kubesphere:kubesphere /var/run/shell-operator

ENV SHELL_OPERATOR_HOOKS_DIR /hooks

ENTRYPOINT ["/shell-operator"]

CMD ["start"]