---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.4.1
spec:
  persistence:
    storageClass: ""        # If there is no default StorageClass in your cluster, you need to specify an existing StorageClass here.
  authentication:
    adminPassword: ""     # Custom password of the admin user. If the parameter exists but the value is empty, a random password is generated. If the parameter does not exist, P@88w0rd is used.
    jwtSecret: ""           # Keep the jwtSecret consistent with the Host Cluster. Retrieve the jwtSecret by executing "kubectl -n kubesphere-system get cm kubesphere-config -o yaml | grep -v "apiVersion" | grep jwtSecret" on the Host Cluster.
    authenticateRateLimiterDuration: 10m0s
    authenticateRateLimiterMaxTries: 10
    oauthOptions:
      accessTokenInactivityTimeout: 60m
      accessTokenMaxAge: 72h
  local_registry: ""        # Add your private registry address if it is needed.
#  dev_tag: ""               # Add your kubesphere image tag you want to install, by default it's same as ks-installer release version.
  etcd:
    monitoring: false       # Enable or disable etcd monitoring dashboard installation. You have to create a Secret for etcd before you enable it.
    endpointIps: localhost  # etcd cluster EndpointIps. It can be a bunch of IPs here.
    port: 2379              # etcd port.
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true  # Enable or disable simultaneous logins. It allows different users to log in with the same account at the same time.
        port: 30880
        type: NodePort

    # apiserver:            # Enlarge the apiserver and controller manager's resource requests and limits for the large cluster
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: false
      enableHA: false
      volumeSize: 2Gi # Redis PVC size.
    openldap:
      enabled: false
      volumeSize: 2Gi   # openldap PVC size.
    minio:
      volumeSize: 20Gi # Minio PVC size.
    monitoring:
      # type: external   # Whether to specify the external prometheus stack, and need to modify the endpoint at the next line.
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090 # Prometheus endpoint to get metrics data.
      GPUMonitoring:     # Enable or disable the GPU-related metrics. If you enable this switch but have no GPU resources, Kubesphere will set it to zero.
        enabled: true
    gpu:                 # Install GPUKinds. The default GPU kind is nvidia.com/gpu. Other GPU kinds can be added here according to your needs.
      kinds:
        # NVIDIA 物理GPU
        - resourceName: nvidia.com/gpu
          displayName: "GPU - Nvidia/英伟达"
          resourceType: GPU
          default: True
          memoryUnit: Mi

        # NVIDIA 虚拟GPU
        - resourceName: nvidia.com/vgpu
          displayName: "vGPU - Nvidia/英伟达"
          resourceType: GPU
          default: False
          memoryUnit: Mi
          memoryName: nvidia.com/gpumem
          vcoresName: nvidia.com/gpucores

        # Cambricon MLU370 物理卡
        - resourceName: cambricon.com/mlu370
          displayName: "MLU370 - Cambricon/寒武纪"
          resourceType: MLU
          default: False

        # Cambricon MLU smlu 虚拟卡
        - resourceName: cambricon.com/vmlu
          displayName: "vMLU - Cambricon/寒武纪"
          resourceType: MLU
          default: False
          memoryUnit: '%'
          memoryName: cambricon.com/mlu.smlu.vmemory
          vcoresName: cambricon.com/mlu.smlu.vcore

        # Cambricon MLU370 共享卡
        - resourceName: cambricon.com/mlu370.share
          displayName: "sMLU370 - Cambricon/寒武纪"
          resourceType: MLU
          default: False

        # 昇腾系列虚拟NPU
        - resourceName: huawei.com/Ascend910A
          displayName: "NPU910A - Ascend/昇腾"
          resourceType: NPU
          default: False
          memoryUnit: Mi
          memoryName: huawei.com/Ascend910A-memory

        - resourceName: huawei.com/Ascend310P
          displayName: "NPU310P - Ascend/昇腾"
          resourceType: NPU
          default: False
          memoryUnit: Mi
          memoryName: huawei.com/Ascend310P-memory

        - resourceName: huawei.com/Ascend910B
          displayName: "NPU910B - Ascend/昇腾"
          resourceType: NPU
          default: False
          memoryUnit: Mi
          memoryName: huawei.com/Ascend910B-memory

        - resourceName: huawei.com/Ascend910B2
          displayName: "NPU910B2 - Ascend/昇腾"
          resourceType: NPU
          default: False
          memoryUnit: Mi
          memoryName: huawei.com/Ascend910B2-memory

        - resourceName: huawei.com/Ascend910B3
          displayName: "NPU910B3 - Ascend/昇腾"
          resourceType: NPU
          default: False
          memoryUnit: Mi
          memoryName: huawei.com/Ascend910B3-memory

        - resourceName: huawei.com/Ascend910B4
          displayName: "NPU910B4 - Ascend/昇腾"
          resourceType: NPU
          default: False
          memoryUnit: Mi
          memoryName: huawei.com/Ascend910B4-memory

        - resourceName: huawei.com/Ascend910B4-1
          displayName: "NPU910B4-1 - Ascend/昇腾"
          resourceType: NPU
          default: False
          memoryUnit: Mi
          memoryName: huawei.com/Ascend910B4-1-memory

        # 海光DCU虚拟卡
        - resourceName: hygon.com/dcunum
          displayName: "DCU - Hygon/海光"
          resourceType: DCU
          default: False
          memoryUnit: Mi
          memoryName: hygon.com/dcumem
          vcoresName: hygon.com/dcucores

        # 天数智芯系列虚拟卡
        - resourceName: iluvatar.ai/MR-V50-vgpu
          displayName: "MR-V50 - Iluvatar/天数"
          resourceType: ILUVATAR
          default: False
          memoryUnit: '*256Mi'
          memoryName: iluvatar.ai/MR-V50.vMem
          vcoresName: iluvatar.ai/MR-V50.vCore

        - resourceName: iluvatar.ai/MR-V100-vgpu
          displayName: "MR-V100 - Iluvatar/天数"
          resourceType: ILUVATAR
          default: False
          memoryUnit: '*256Mi'
          memoryName: iluvatar.ai/MR-V100.vMem
          vcoresName: iluvatar.ai/MR-V100.vCore

        - resourceName: iluvatar.ai/BI-V100-vgpu
          displayName: "BI-V100 - Iluvatar/天数"
          resourceType: ILUVATAR
          default: False
          memoryUnit: '*256Mi'
          memoryName: iluvatar.ai/BI-V100.vMem
          vcoresName: iluvatar.ai/BI-V100.vCore

        - resourceName: iluvatar.ai/BI-V150-vgpu
          displayName: "BI-V150 - Iluvatar/天数"
          resourceType: ILUVATAR
          default: False
          memoryUnit: '*256Mi'
          memoryName: iluvatar.ai/BI-V150.vMem
          vcoresName: iluvatar.ai/BI-V150.vCore

        - resourceName: iluvatar.ai/BI-V150S-vgpu
          displayName: "BI-V150S - Iluvatar/天数"
          resourceType: ILUVATAR
          default: False
          memoryUnit: '*256Mi'
          memoryName: iluvatar.ai/BI-V150S.vMem
          vcoresName: iluvatar.ai/BI-V150S.vCore

        # 沐曦METAX物理卡
        - resourceName: metax-tech.com/gpu
          displayName: "METAX - Metax/沐曦"
          resourceType: METAX
          default: False

        # 沐曦vMETAX虚拟卡
        - resourceName: metax-tech.com/sgpu
          displayName: "vMETAX - Metax/沐曦"
          resourceType: METAX
          default: False
          memoryUnit: Gi
          memoryName: metax-tech.com/vmemory
          vcoresName: metax-tech.com/vcore

        # 燧原GCU物理卡
        - resourceName: enflame.com/gcu
          displayName: "GCU - Enflame/燧原"
          resourceType: GCU
          default: False

        # 燧原vGCU虚拟卡
        - resourceName: enflame.com/vgcu
          displayName: "vGCU - Enflame/燧原"
          resourceType: GCU
          default: False
          vcoresName: enflame.com/vgcu-percentage

        # 阿里巴巴PPU物理卡
        - resourceName: alibabacloud.com/ppu
          displayName: "PPU - Alibaba/阿里巴巴"
          resourceType: PPU
          default: False

        # 摩尔线程vMTHREADS虚拟卡
        - resourceName: mthreads.com/vgpu
          displayName: "vMTHREADS - Mthreads/摩尔线程"
          resourceType: MTHREADS
          default: False
          memoryUnit: '*512Mi'
          memoryName: mthreads.com/sgpu-memory
          vcoresName: mthreads.com/sgpu-core

        # 昆仑芯XPU物理卡
        - resourceName: kunlunxin.com/xpu
          displayName: "XPU - Kunlunxin/昆仑芯"
          resourceType: XPU
          default: False

        # 昆仑芯vXPU虚拟卡
        - resourceName: kunlunxin.com/vxpu
          displayName: "vXPU - Kunlunxin/昆仑芯"
          resourceType: XPU
          default: False
          memoryUnit: Mi
          memoryName: kunlunxin.com/vxpu-memory
    es:   # Storage backend for logging, events and auditing.
      # master:
      #   volumeSize: 4Gi  # The volume size of Elasticsearch master nodes.
      #   replicas: 1      # The total number of master nodes. Even numbers are not allowed.
      #   resources: {}
      # data:
      #   volumeSize: 20Gi  # The volume size of Elasticsearch data nodes.
      #   replicas: 1       # The total number of data nodes.
      #   resources: {}
      enabled: false
      logMaxAge: 7             # Log retention time in built-in Elasticsearch. It is 7 days by default.
      elkPrefix: logstash      # The string making up index names. The index name will be formatted as ks-<elk_prefix>-log.
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
    opensearch:   # Storage backend for logging, events and auditing.
      # master:
      #   volumeSize: 4Gi  # The volume size of Opensearch master nodes.
      #   replicas: 1      # The total number of master nodes. Even numbers are not allowed.
      #   resources: {}
      # data:
      #   volumeSize: 20Gi  # The volume size of Opensearch data nodes.
      #   replicas: 1       # The total number of data nodes.
      #   resources: {}
      enabled: true
      logMaxAge: 7             # Log retention time in built-in Opensearch. It is 7 days by default.
      opensearchPrefix: whizard      # The string making up index names. The index name will be formatted as ks-<opensearchPrefix>-logging.
      basicAuth:
        enabled: true
        username: "admin"
        password: "admin"
      externalOpensearchHost: ""
      externalOpensearchPort: ""
      dashboard:
        enabled: true
  alerting:                # (CPU: 0.1 Core, Memory: 100 MiB) It enables users to customize alerting policies to send messages to receivers in time with different time intervals and alerting levels to choose from.
    enabled: true         # Enable or disable the KubeSphere Alerting System.
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:                # Provide a security-relevant chronological set of records，recording the sequence of activities happening on the platform, initiated by different tenants.
    enabled: true         # Enable or disable the KubeSphere Auditing Log System.
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:                  # (CPU: 0.47 Core, Memory: 8.6 G) Provide an out-of-the-box CI/CD system based on Jenkins, and automated workflow tools including Source-to-Image & Binary-to-Image.
    enabled: false         # Enable or disable the KubeSphere DevOps System.
    jenkinsCpuReq: 0.5
    jenkinsCpuLim: 1
    jenkinsMemoryReq: 4Gi
    jenkinsMemoryLim: 4Gi  # Recommend keep same as requests.memory.
    jenkinsVolumeSize: 16Gi
  events:                  # Provide a graphical web console for Kubernetes Events exporting, filtering and alerting in multi-tenant Kubernetes clusters.
    enabled: true         # Enable or disable the KubeSphere Events System.
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    ruler:
      enabled: true
      replicas: 2
    #   resources: {}
  logging:                 # (CPU: 57 m, Memory: 2.76 G) Flexible logging functions are provided for log query, collection and management in a unified console. Additional log collectors can be added, such as Elasticsearch, Kafka and Fluentd.
    enabled: true         # Enable or disable the KubeSphere Logging System.
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:                    # (CPU: 56 m, Memory: 44.35 MiB) It enables HPA (Horizontal Pod Autoscaler).
    enabled: false                   # Enable or disable metrics-server.
  monitoring:
    storageClass: ""                 # If there is an independent StorageClass you need for Prometheus, you can specify it here. The default StorageClass is used by default.
    node_exporter:
      port: 9100
      # resources: {}
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1  # Prometheus replicas are responsible for monitoring different segments of data source and providing high availability.
    #   volumeSize: 20Gi  # Prometheus PVC size.
    #   resources: {}
    #   operator:
    #     resources: {}
    # alertmanager:
    #   replicas: 1          # AlertManager Replicas.
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:                           # GPU monitoring-related plug-in installation.
      nvidia_dcgm_exporter:        # Ensure that gpu resources on your hosts can be used normally, otherwise this plug-in will not work properly.
        enabled: false             # Check whether the labels on the GPU hosts contain "nvidia.com/gpu.present=true" to ensure that the DCGM pod is scheduled to these nodes.
        # resources: {}
      mlu_exporter:                # Cambricon MLU exporter for MLU device monitoring.
        enabled: false             # Enable or disable the Cambricon MLU exporter.
        # resources: {}
  multicluster:
    clusterRole: none  # host | member | none  # You can install a solo cluster, or specify it as the Host or Member Cluster.
  network:
    networkpolicy: # Network policies allow network isolation within the same cluster, which means firewalls can be set up between certain instances (Pods).
      # Make sure that the CNI network plugin used by the cluster supports NetworkPolicy. There are a number of CNI network plugins that support NetworkPolicy, including Calico, Cilium, Kube-router, Romana and Weave Net.
      enabled: false # Enable or disable network policies.
    ippool: # Use Pod IP Pools to manage the Pod network address space. Pods to be created can be assigned IP addresses from a Pod IP Pool.
      type: none # Specify "calico" for this field if Calico is used as your CNI plugin. "none" means that Pod IP Pools are disabled.
    topology: # Use Service Topology to view Service-to-Service communication based on Weave Scope.
      type: none # Specify "weave-scope" for this field to enable Service Topology. "none" means that Service Topology is disabled.
  openpitrix: # An App Store that is accessible to all platform tenants. You can use it to manage apps across their entire lifecycle.
    store:
      enabled: false # Enable or disable the KubeSphere App Store.
  servicemesh:         # (0.3 Core, 300 MiB) Provide fine-grained traffic management, observability and tracing, and visualized traffic topology.
    enabled: false     # Base component (pilot). Enable or disable KubeSphere Service Mesh (Istio-based).
    istio:  # Customizing the istio installation configuration, refer to https://istio.io/latest/docs/setup/additional-setup/customize-installation/
      components:
        ingressGateways:
        - name: istio-ingressgateway
          enabled: false
        cni:
          enabled: false
  edgeruntime:          # Add edge nodes to your cluster and deploy workloads on edge nodes.
    enabled: false
    kubeedge:        # kubeedge configurations
      enabled: false
      cloudCore:
        cloudHub:
          advertiseAddress: # At least a public IP address or an IP address which can be accessed by edge nodes must be provided.
            - ""            # Note that once KubeEdge is enabled, CloudCore will malfunction if the address is not provided.
        service:
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudhubHttpsNodePort: "30002"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
        # resources: {}
        # hostNetWork: false
      iptables-manager:
        enabled: true 
        mode: "external"
        # resources: {}
      # edgeService:
      #   resources: {}
  gatekeeper:        # Provide admission policy and rule management, A validating (mutating TBA) webhook that enforces CRD-based policies executed by Open Policy Agent.
    enabled: false   # Enable or disable Gatekeeper.
    # controller_manager:
    #   resources: {}
    # audit:
    #   resources: {}
  terminal:
    image: 'alpine:3.23' # There must be an nsenter program in the image
    timeout: 600         # Container timeout, if set to 0, no timeout will be used. The unit is seconds
