---
- name: Monitoring | Getting GPU monitoring installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - "gpu-monitoring"
  when: monitoring.gpu is defined and monitoring.gpu.enabled | default(false) | bool

- name: Monitoring | Installing custom gpu dashboards
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/gpu-monitoring/gpu-dashboards/  --force
  when: monitoring.gpu is defined and monitoring.gpu.enabled | default(false) | bool

- name: Monitoring | Installing gpu-agent exporter ServiceMonitor
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/gpu-monitoring/gpu-agent-service-monitor.yaml --force
  when: monitoring.gpu is defined and monitoring.gpu.enabled | default(false) | bool

- name: Monitoring | Installing GPU PrometheusRule
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/prometheus/gpu --force
  when: monitoring.gpu is defined and monitoring.gpu.enabled | default(false) | bool
