---

- import_tasks: init-namespaces.yaml


- name: KubeAIHub | Getting Kubernetes master num
  shell: >
    {{ bin_dir }}/kubectl get node | awk '{if(NR>1){print $3}}' | grep -E 'master|control-plane' | wc -l
  register: masters
  failed_when: false


- name: KubeAIHub | Setting master num
  set_fact:
    enableHA: >-
      {% if masters is defined and masters.stdout is defined and masters.stdout != "0" and masters.stdout != "1" %}true{% else %}false{% endif %}
  when:
    - enableHA is not defined

- name: KubeAIHub | Getting common component installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - "common"

- name: KubeAIHub | Checking Kubernetes version
  shell: >
    {{ bin_dir }}/kubectl version -o json | jq -r '.serverVersion.gitVersion'
  register: kubernetes_version

- name: KubeAIHub | Deploying snapshot controller
  block:
    - name: KubeAIHub | Getting common component installation files
      copy:
        src: "{{ item }}"
        dest: "{{ kubesphere_dir }}/"
      loop:
        - "snapshot-controller"

    - name: KubeAIHub | Creating snapshot controller values
      template:
        src: "{{ item.file }}.j2"
        dest: "{{ kubesphere_dir }}/{{ item.file }}"
      with_items:
        - { name: custom-values-snapshot-controller, file: custom-values-snapshot-controller.yaml }

    - name: KubeAIHub | Updating snapshot crd
      command: >
        {% if kubernetes_version is version('v1.24.0', '>=') %}
        {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/snapshot-controller/crds/snapshot.storage.k8s.io_volumesnapshot.yaml --force
        {% else %}
        {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/snapshot-controller/crds/snapshot.storage.k8s.io_volumesnapshot_before119.yaml --force
        {% endif %}
      failed_when: false

    - name: KubeAIHub | Deploying snapshot controller
      shell: >
        {{ bin_dir }}/helm upgrade --install snapshot-controller
        {{ kubesphere_dir }}/snapshot-controller
        -f {{ kubesphere_dir }}/custom-values-snapshot-controller.yaml
        --namespace kube-system
      failed_when: false

  when:
    - kubernetes_version is version('v1.17.0', '>=')


- name: KubeAIHub | Checking openpitrix common component
  shell: >
    {{ bin_dir }}/kubectl get pod -n openpitrix-system
  register: openpitrix_component_pod


- include_tasks: pv-migration.yaml
  loop:
    - {op: "openpitrix-db", ks: "mysql-pvc"}
    - {op: "openpitrix-etcd", ks: "etcd-pvc"}
#    - {openpitrix: "openpitrix-minio", ks: "minio-pvc"}
  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") != -1


- name: KubeAIHub | Getting PersistentVolumeName (mysql/etcd/minio)
  block:

    - name: Getting PersistentVolumeName (mysql)
      shell: >
        kubectl get pv | grep "kubesphere-system/mysql-pvc" | awk '{print $1}'
      register: pvName
    - name: Getting PersistentVolumeSize (mysql)
      shell: >
        kubectl get pv | grep "kubesphere-system/mysql-pvc" | awk '{print $2}'
      register: pvSize

    - name: Setting PersistentVolumeName (mysql)
      set_fact:
        db_pv_name: "{{ pvName.stdout }}"
    - name: Setting PersistentVolumeSize (mysql)
      set_fact:
        common:
          mysqlVolumeSize: "{{ pvSize.stdout }}"


    - name: Getting PersistentVolumeName (etcd)
      shell: >
        kubectl get pv | grep "kubesphere-system/etcd-pvc" | awk '{print $1}'
      register: pvName
    - name: Getting PersistentVolumeSize (etcd)
      shell: >
        kubectl get pv | grep "kubesphere-system/etcd-pvc" | awk '{print $2}'
      register: pvSize

    - name: Setting PersistentVolumeName (etcd)
      set_fact:
        etcd_pv_name: "{{ pvName.stdout }}"
    - name: Setting PersistentVolumeSize (etcd)
      set_fact:
        common:
          etcdVolumeSize: "{{ pvSize.stdout}}"


  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") != -1

- import_tasks: get_old_config.yaml

- name: KubeAIHub | Creating common component manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/common/{{ item.file }}"
  with_items:
#    - { path: etcd, file: etcd.yaml }
#    - { name: mysql, file: mysql.yaml }
    - { path: redis, file: redis.yaml }


#- name: KubeAIHub | Creating mysql sercet
#  shell: >
#    {{ bin_dir }}/kubectl create secret generic mysql-pass
#    --from-file={{ kubesphere_dir }}/common/password.txt
#    -n kubesphere-system
#  register: import
#  failed_when: "import.stderr and 'already exists' not in import.stderr"

- name: KubeAIHub | Deploying common component
  block:
    - name: KubeAIHub | Deploying etcd and mysql
      shell: >
        {{ bin_dir }}/kubectl -n kubesphere-system apply -f {{ kubesphere_dir }}/common/{{ item }}
      loop:
        - "etcd.yaml"
        - "mysql.yaml"
      register: common_result
      failed_when:
        - "common_result.stderr and 'is immutable after creation except resources.requests for bound claims' not in common_result.stderr"
        - "common_result.stderr and 'is forbidden' not in common_result.stderr"


    - import_tasks: minio-install.yaml


    - import_tasks: redis-install.yaml


    - import_tasks: openldap-install.yaml

  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") != -1


- import_tasks: common-install.yaml
  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") == -1


- name: KubeAIHub | Setting persistentVolumeReclaimPolicy (mysql/etcd/minio)
  block:

    - name: Setting persistentVolumeReclaimPolicy (mysql)
      shell: >
        kubectl patch pv $(kubectl get pv | grep "mysql-pvc" | awk '{print $1}')
        -p '{"spec":{"persistentVolumeReclaimPolicy": "Delete"}}'

    - name: Setting persistentVolumeReclaimPolicy (etcd)
      shell: >
        kubectl patch pv $(kubectl get pv | grep "etcd-pvc" | awk '{print $1}')
        -p '{"spec":{"persistentVolumeReclaimPolicy": "Delete"}}'

  when:
    - openpitrix_component_pod.stdout.find("openpitrix-db-deployment") != -1
