apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dcgm-exporter.fullname" . }}
  labels:
    {{- include "dcgm-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: "dcgm-exporter"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
